### ISSUE TITLE
Version number confusion

### ISSUE THREAD

**Issue by marshall-ucsd** [pyscripter/pyscripter#1007]
On SourceForge, the most current PyScripter release to download is _3.6.3_ (Jan 2020)
But under GitHub releases, 3.6.3 is not actually listed. Furthermore, there is a new _3.6.2.1_ release listed on GitHub.
So, what _is_ the actual current PyScripter (stable) release?

**Comment by pyscripter** [comment]
GitHub releases are source code only.  Most users are not interested in those.
Binary releases are always in SourceForge.   They usually correspond to source releases in Github, but this is not always the case.

And in case you ask why we do not have binary releases in Github, it is because Github does not provide for easy tracking of downloads.
