### ISSUE TITLE
pip issue

### ISSUE THREAD

**Issue by ystartgo** [pyscripter/pyscripter#1144]
how to pip package?
in version 4.0.0.6 if try to pip in tools/tools/install packages... 
try to pip  any package 
show
Command line: I:\Download\Python_Portable\App\Python\Scripts\pip.exe install -U pip install pkglts
Working directory: 
Timeout: 0 ms

Process "Install Packages with pip" terminated, ExitCode: 00000001

pip works normally in 3.6.4.0 version.

**Comment by pyscripter** [comment]
When you did Tools, Install packages with pip,  in the dialog box, you typed "pip install pkglts" instead of just "pkglts".

If that was not the case then go to Tools, Configure Tools, and select "Install Packages with pip".   Make sure:
  ApplIcation is "$[PythonDir-Short]Scripts\pip.exe"
  Parameters is "install -U $[Package?Package Name]"

**Comment by ystartgo** [comment]
Hi ,
I use old setting at ver 4.0.0.6
[Tools\Tool1\ExternalTool]
Caption=Install Packages with pip
Description=Install Python packages
ApplicationName=$[PythonExe-Short]
Parameters=$[PythonDir-Short]Lib\site-packages\pip install $[Package?Package Name]
in PyScripter.ini can run pip

**Comment by pyscripter** [comment]
ApplIcationName=$[PythonDir-Short]Scripts\pip.exe
Parameters=install -U $[Package?Package Name]

would also work.  Just make sure that when prompted you type just the package name.

> Command line: I:\Download\Python_Portable\App\Python\Scripts\pip.exe install -U pip install pkglts

The above is the result of typing "pip install pkglts" instead of just  "pkglts"
