### ISSUE TITLE
go to definition issue after I double click on a symbol

### ISSUE THREAD

**Issue by asmwarrior** [pyscripter/pyscripter#1151]
Hi, if I use the mouse to double click on a symbol, the caret automatically put after the symbol, then if I try to find the definition of the symbol, it will give you a message box that the caret should be put inside the symbol. This is not quite expect behavior.

I think if I double click on the symbol, then open the context menu and click the go to definition, it should go to the definition instead of pop up a message box.

See the screen cast below:
![go_to_definition1](https://user-images.githubusercontent.com/561818/144702404-1c0cc379-9196-462d-941c-28337df03f5d.gif)

**Comment by asmwarrior** [comment]
Another issue is that if I double click on a symbol, the symbol is highlighted, but how can I cancel the highlight? Thanks.

**Comment by pyscripter** [comment]
This regression will be fixed in the next version.

Please note:

-  It is much simpler to Ctrl+Click to find the definition of an Identifier.   i.e. click with the mouse on an identifier while pressing the Ctrl button.  This works has the advantage of working with the Browse Back/Forward buttons on the toolbar.  You can press the Browse Back button (or press Alt+Left)  to move back to the original position.
-  The Search highlight will be removed as soon as you type anything.  Otherwise it can be removed by pressing the second button from the end in the Find Toolbar (Ctrl+F).

**Comment by asmwarrior** [comment]
OK, thanks for the info.
I think this issue can be closed if the regression is fixed.

**Comment by asmwarrior** [comment]
Thanks for the fix!

Do you have any nightly build versions of pyscripter? So that people can try those new features.

**Comment by pyscripter** [comment]
I am afraid not.  But the new version will be out in just a few days.
