### ISSUE TITLE
I can't add a new python version.

### ISSUE THREAD

**Issue by sbharuchi** [pyscripter/pyscripter#1179]
I can't add a new python version.
Error Message: PyScripter could not find a usable Python installation at the specified path.

Python version: 3.10

See attached screen shot.

![pyscripter msg](https://user-images.githubusercontent.com/115969063/196575971-549b65cd-656b-478a-9b20-9d15eae222c8.JPG)

**Comment by pyscripter** [comment]
This typically happens when one of the following things happen:
-  Python is not properly installed.  PyScripter requires that a python distribution (e.g. from www.python.org) is installed in your machine.
- The bitness of Python does not match the bitness of PyScripter.  e.g.  PyScripter 64 bits works only with python 64 bits and PyScripter 32 bits works only with python 32 bits.


Which versions of PyScritper/python are you trying to use together?

**Comment by sbharuchi** [comment]
**Computer Version:**

Device name	DESKTOP-E46IFNS
Processor	Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz
Installed RAM	12.0 GB (11.8 GB usable)
Device ID	ED0C8470-D21C-45B5-896C-8E081B595D04
Product ID	00325-96696-42399-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points

**Python Version:**

Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
![pyscripter version](https://user-images.githubusercontent.com/115969063/196832676-0db958c3-7d41-4187-b9bd-c15c97a71183.JPG)

Pyscripter Version - see screenshot
Downloaded from: https://sourceforge.net/projects/pyscripter/files/

As far I can tell, both are 64 bits.
