### ISSUE TITLE
Splitting Pyscripter up

### ISSUE THREAD

**Issue by Dave-Novo** [pyscripter/pyscripter#1294]
Hello.

I am looking into how I can split up pyscripter in order to embed a functional python scripting engine into my Delphi application.

Looking into frmPyIDEMain.pas, it does not seem like this should be a terrible job.

The overall approach I would take would be to simply move most of the non-toolbar related stuff onto a TFrame descendent. Then, in another application if I wanted to include python scripting, I just have to register the frame with the IDE.

The actStandard actionlist would stay on the TFrame. That way, the only thing that would really happen in frmPyIDEMain would be to hook up the actions to the toolbar2000.

This opens up some nice possibilities if someone wants to make a pyscripter with a ribbon for example, they just drop the frame on a devExpress ribbon form and hook up the action lists. 

I am not familiar enough yet with the AppStorage to know what it is storing so I am not sure if that belongs in the TFrame or not. 

A lot of details, i.e. can a dockServer be hosted by a TFrame or not.

What do you think of this approach?

**Comment by pyscripter** [comment]
When I started writing PyScripter many years back the original intention was to create a python scripting environment for Delphi apps, like VBA was for Office apps.  Since then PyScripter has grown into a complex stand-alone IDE.   Turning it an embeddable environment is possible, but it would take a lot of work and a good understanding of the code. 

Regarding your question the UI is a matter of taste.  It could remain a stand-alone window (like VBA) or a Frame that could more easily integrate with the hosting app's UI.   However if you plan to still use the dockable IDE windows the first solution would be simpler to implement.   I am not sure whether the dockable library works with a Frame as the parent but I guess it could.   You might want to replace it though with standard Delphi docking like in Delphi IDE.  It would then be easier to integrate with different Delphi hosts.

**Comment by Dave-Novo** [comment]
It seems like jvDocking works almost perfectly on a TFrame. The only problem is that the caption of the docked form is not rendered correctly. 
The built in Delphi docking is fairly terrible. It is simple to set up, but once you set a client frame to dragKind=dkDock, the form drags so slowly that it is terrible.
