### ISSUE TITLE
Mouse-wheel scrolling in 'Find:'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#655]
```
What steps will reproduce the problem?
1. Press Ctrl+F
2. Enter some text
3. Place mouse cursor over source-code
4. Scroll with mouse-wheel.

What is the expected output? What do you see instead?
Expected: source-code scrolled.
Instead: switching between find-phrases.

What version of the product are you using? On what operating system?
Verision 2.5.3.0 x86 on WinXP SP3 32-bit
```

Original issue reported on code.google.com by `breaker....@gmail.com` on 13 May 2012 at 9:22

**Comment by pyscripter** [comment]
Note to myself.
https://stackoverflow.com/questions/2251019/how-to-direct-the-mouse-wheel-input-to-control-under-cursor-instead-of-focused

**Comment by pyscripter** [comment]
On Windows 10 this is no longer an issue.  This is due to a new mouse setting called "Scroll inactive windows", which is on by default.  See https://www.thurrott.com/windows/windows-10/2435/windows-10-tip-scroll-inactive-windows for details.

Since resolving this issue would be quite complex and the vast majority of users are on Windows 10, I am closing this issue.
