### ISSUE TITLE
Color theme minor issue / Syntax highlighting

### ISSUE THREAD

**Issue by Noomene** [pyscripter/pyscripter#833]
Hello devs,

First of all, congratulations for PyScripter, it's my favorite Python IDE right now!

I just wanted to draw your attention to one issue with themes and syntax highlighting. As you can see on [this screenshot](https://pasteboard.co/GWtm4vx.png), there are major discrepancies between the wanted theme / syntax color and the actual one implemented in the editor. Notice the color of the reserved word `print`. Also notice the font use, one is sans serif and the other is serif (that being said, sans serif in the editor is the right choice for me). And I'm sure there are other minor discrepancies if the sample code was bigger. 

This is probably a very minor consistency issue. And hopefully the fix is also minor.

Thank you guys again for your work.

Regards,

**Comment by pyscripter** [comment]
Thanks for the report.   The Syntax Colors part of the editor options dialog is only about the colors of the different elements of a programming language.  The editor font is selected elsewhere. (in the "Display" page of the dialog).  This is why no effort is taken to match the font with the one used in the editor, especially since you may use different fonts in different editors.
 
Regarding the highlighting of "print".  In Python 3.x print is not a keyword, so it is correctly not highlighted as such if you use Pyscripter with a 3.x version of Python.  Unfortunately, the highlighter
in the editor options dialog is a simplified version of the one used in the editor and uses a stock list of keywords in which "print" is included.  What I will do to avoid the confusion, is change the sample python code to not include "print".  In fact the current sample code would not compile in python 3.x.

**Comment by Noomene** [comment]
Thank you for a clear and excellent reply!
