### ISSUE TITLE
Feature request: Open folder as workspace

### ISSUE THREAD

**Issue by SoraTheDev** [pyscripter/pyscripter#839]
I think it would be nice to add an option to open a folder as a workspace.

**Comment by pyscripter** [comment]
PyScriptrer calls Workspaces Projects.
There are two ways to achieve this.
a) Go to the Project Explrorer, right click on Files or a subfolder of Files and select Import Directory.
b)  Dock the Project Explorer to a different side than the File Explorer so that you can see both.  Then drag and drop of a File Explorer folder onto the Project Explorer's Files node or a subfolder of this node.
