### ISSUE TITLE
A Big Thanks

### ISSUE THREAD

**Issue by tanmayameher** [pyscripter/pyscripter#842]
Thank you for including my color schemes directly into this fantastic project. I have created some almost 4 years ago. But, i stopped those thinking pyscripter dead; as there were no updates at that time. Good to know that you guys have updated it and now it's good too.

Though, i rarely use windows now; i will still create some color schemes (from eclipse color schemes pages or vim color scheme pages available online) and some entirely new color schemes ( i will try at least :D ) as soon as i get some time.

I invite everyone to contribute to this project and to [my color scheme page](https://github.com/tanmayameher/PyScripter-Color-Schemes) too; to make it stay updated with this project. :)

Thanks again :)

**Comment by pyscripter** [comment]
The big thanks you goes to your for your contribution.    I will leave this "issue" open for now to remember to add you to the list of contributors.   Just a few tips:

- Please read this [blog post](https://pyscripter.blogspot.gr/2017/12/adjust-darkness-to-your-taste.html) especially regarding the role of the foreground color or the Space attribute.
- It is usefule to set the background color of most attributes to clNone, so that they adjust when you change the background of the Space attribute.
- There is now a General highlighter with just a small number of color attributes that is used to paint plain text files.
- It would be nice to make consistent color themes for some or the other syntax schemes such as YAML.
- It is now easier to import color themes through Editor Options, Color themes.  Additional color themes should be placed at the directory %APPDATA%\PyScripter\Highlighters

**Comment by tanmayameher** [comment]
Thank you so much. That means a lot to me :) 🥇 

Ooh.So, now user can lighten / darken according to their wish (according to brightness/darkness their eye is comfortable with). That's a nice feature. But, isn't it stay white or something if i don't set the background?

For instance, let's say i want to create a sky color theme (which needs to have a sky blue background), so that the darker or other slightly darker syntax get highlighted properly, if it gets to completely white by setting it to clNone won't it look bad and may hurt eye even more, because of increase in contrast between dark syntax and background ?! (like solarized color schemes which are made after quite a bit of research on color, lab color space and visual perception etc.). Am i getting it or i understood something else from that blog post? 

great. Now, i can make some color schemes for plain text files too. 👍 

Yes, it would be nice to make those color schemes consistent across all programming languages that pyscripter supports. sure i will consider that while doing it :)

**Comment by pyscripter** [comment]
The background color of the Space attribute is used as the background color of all other attributes that have background color clNone.  So they are not white.  You can control the background color of all elements of a language by the background color of Space.   (Have I understood your question?)

**Comment by pyscripter** [comment]
I have added credits to you in the About box and the help file.
