### ISSUE TITLE
Column number not showing

### ISSUE THREAD

**Issue by FrancisTinLoi** [pyscripter/pyscripter#983]
Hi Kiriakos:

PyScripter 3.6.2.0 x64. Windows 7 OS.
When the line number is large (e.g. 3 digits) and the column number has 2 digits, the column number is no longer displayed in the status bar. See attached jpg.

Thanks -- Francis

![column](https://user-images.githubusercontent.com/59784277/72213763-c529f480-3548-11ea-9f6b-e114acd914b5.JPG)

**Comment by pyscripter** [comment]
However, after further investigation I have found the cause of this problem. It's caused by my one of my Win 7 "Window Color and Appearance" setups. For the "Menu"  item I had the font as "Trebuchet, 11 pt, bold". This is too big to fit the "line:col" data. Simply changing this for instance to "Segoe UI, 11pt, bold" allows the "line:col" info to be displayed!

Still, would be nice, for the next release of this excellent product, to simply allow for more characters to fit in the "line:col" space.
